name: Generate Sitemap

on:
  schedule:
    - cron: '0 1 * * *' # Runs daily at 1 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
        run: npm install node-fetch
      - name: Generate sitemap.xml
        run: node scripts/generate-sitemap.js
      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap [skip ci]" || echo "No changes"
          git push
